version: '3.8'

services:
  backend:
    build: .
    network_mode: "host" # <--- The Magic Fix. Uses your real internet.
    env_file:
      - .env
    depends_on:
      - ai-service

  ai-service:
    build: ./ai-service
    network_mode: "host" # <--- The Magic Fix.
    env_file:
      - .env